version: '2'
services:
  
  master:
    build: .
    command: "npm run master"
  
    environment:
      - REDIS_URL= redis://redis

    depends_on:
     - redis
     - worker-creator
     - worker-activity

    links:
     - redis

  worker-creator:
    build: .
    command: "npm run worker-creator"

    environment:
      - REDIS_URL= redis://redis

    depends_on:
     - redis
     - worker-activity

    links:
     - redis

  worker-activity:
    build: .
    command: "npm run worker-activity"

    environment:
      - REDIS_URL= redis://redis

    depends_on:
     - redis

    links:
     - redis
  
  redis:
    image: redis
