version: '2'
services:
  
  master:
    build: .
    command: "npm run master"
  
    environment:
      - REDIS_HOST=redis
      - API_URL=http://67.205.130.0:80
      - SOCKET_HOST=ws://67.205.130.0
      - SOCKET_PATH=/api/1.0/socket
      - TIME=1800
      - NUMBER_COMPANIES=1
      - NUMBER_USERS=1000
    depends_on:
     - worker-creator
     - worker-activity

    links:
     - redis

  worker-creator:
    build: .
    command: "npm run worker-creator"

    environment:
      - REDIS_HOST=redis

    depends_on:
     - worker-activity

    links:
     - redis

  worker-creator-sync:
    build: .
    command: "npm run worker-creator-sync"

    environment:
      - REDIS_HOST=redis

    depends_on:
     - worker-activity

    links:
     - redis

  worker-activity:
    build: .
    command: "npm run worker-activity"

    environment:
      - REDIS_HOST=redis

    links:
     - redis
  
  redis:
    image: redis
