version: '2'
services:
  
  master:
    build: .
    command: "npm run master"
  
    environment:
      - REDIS_HOST=redis
      - API_URL=http://td-rest-api.herokuapp.com:80
      - SOCKET_URL=wss://td-rest-api.herokuapp.com/api/1.0/socket/
      - TIME=1800
      - NUMBER_COMPANIES=1
      - NUMBER_USERS=100
    depends_on:
     - worker-creator
     - worker-activity

    links:
     - redis

  worker-creator:
    build: .
    command: "npm run worker-creator"

    environment:
      - REDIS_HOST=redis

    depends_on:
     - worker-activity

    links:
     - redis

  worker-activity:
    build: .
    command: "npm run worker-activity"

    environment:
      - REDIS_HOST=redis

    links:
     - redis
  
  redis:
    image: redis